package HashTable.FindTheDifference_389;

import java.util.HashSet;
import java.util.Set;

/**
 389. Find the Difference

 Given two strings s and t which consist of only lowercase letters.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Find the letter that was added in t.

 Example:
 Input:
 s = "abcd"
 t = "abcde"
 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */

class Solution {
    public char findTheDifference1(String s, String t) {
        int len = t.length() - 1;

        int[] characters = new int[26];

        for (int i = 0; i < len; i++) {
            characters[s.charAt(i) - 'a']++;
        }

        for (int i = 0; i <= len; i++) {
            int index = t.charAt(i) - 'a';

            characters[index]--;

            if (characters[index] < 0) {
                return t.charAt(i);
            }
        }

        return t.charAt(len);
    }

    public char findTheDifference(String s, String t) {
        int result = 0;
        for (int i = 0; i < t.length() - 1; i++) {
            result = result - (s.charAt(i) - 'a') + (t.charAt(i) - 'a');
        }

        result += t.charAt(t.length() - 1) - 'a';

        return (char) (result + 'a');
    }
}